services:
  app-fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8888:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres-db-fastapi:5432/postgres"
    networks:
      - app-fastapi
      - database-fastapi_postgres-database


networks:
  app-fastapi:
    driver: bridge

  database-fastapi_postgres-database:
    external: true