version: '3.3'


services:
  app-fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8888:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres-db-fastapi:5432/postgres"
    networks:
      - app-fastapi
      - database-fastapi_postgres-database

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-fastapi

networks:
  app-fastapi:
    driver: bridge

  database-fastapi_postgres-database:
    external: true
